apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital
type: Opaque
stringData:
  DB_DATABASE: hospital_db
  DB_USERNAME: hospital_user
  DB_PASSWORD: password
  APP_KEY: base64:f0ZLjftlF7u9kM0dKXlsKXOSoX7rcU9HlCmN7qIKxYk=

